---
title: "Homework: Awesomely Bad Graphics"
author: "Your Name"
format:
  html:
    theme: default
---



## Take everything you know, and use it for evil

The textbook spent lots of time showing you how to create different types of graphics, but I spent a lot less time showing you all of the different ways you could customize graphics `ggplot2` or `plotnine`. In this problem, I want you to create the *ugliest* version of the following graphs you can, and then **explain why**, exactly, you made the decisions you did, and which principles of good graphics you've intentionally violated.

Ugliness is subjective, so the goal here is for you to explore the different ways you can customize the finer details of graphics. Make sure your finished masterpiece has appropriate axis labels and a title (after all, even ugly plots need to be correctly labeled!). You are free to add additional variables and layers, modify the aesthetics used, and leverage other packages. I have provided this code as a starting point, not as a way to limit your creativity.

I have provided some basic code to get you started. We'll use the `palmerpenguins` package, which has [fantastic documentation with really awesome artwork](https://allisonhorst.github.io/palmerpenguins/).

```{r}
if (!"palmerpenguins" %in% installed.packages()) {
  remotes::install_github("allisonhorst/palmerpenguins")
}
library(palmerpenguins)
library(ggplot2)

head(penguins)

ggplot(penguins, aes(x = body_mass_g, y = bill_length_mm, color = species)) +
  geom_point()
```

```{python}
penguins = r.penguins
```




### Useful References

- [Customizing ggplot2 graphics](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part2-Customizing-Theme-With-R-Code.html)

- [A group-created slideshow of awful graphics](https://docs.google.com/presentation/d/1ixRsGI8BWgT2zA5AbB61eMLUbJgObvBCZt-OnZDzvX4/edit?usp=sharing)

- [An example of customizing plots in plotnine](https://t-redactyl.io/blog/2020/09/making-beautiful-boxplots-using-plotnine-in-python.html)

